= OAuth 2.0 - Authorization Code Flow - Lab Solutions

*Q: What did the NodeJS Application response to the HTTP GET Request for http://localhost:3001/techlab-service/secured and which action will the browser do next?*

A: The NodeJS backend (better: the client adapter embedded in NodeJS backend) creates a redirect URL which the User Agent will be redirected to. The generated redirection URL contains the following parameters

* `client_id=techlab-cli`: The defined Client ID. Must be registered previously in Keyloak.
* `response_type=code`: The response should contain an Authorization Code
* `redirect_uri=http%3A%2F%2Flocalhost%3A3001%2Ftechlab-service%2Fsecured%3Fauth_callback%3D1`: URL to which Keycloak should redirect the End-User after the authorization was successful.
* `state=0ee4b7b6-f5c5-499b-9936-7cb348ae6f19`: Random String to match the client requests and redirected response from Keycloak.
* `scope=openid`: Enabling OpenID connect.


=== Captured Flow

. End-User requests the Protected Resource, receives a HTTP 302 Redirection to Login Form provided by Keycloak
+
[source,http]
----
HTTP GET http://localhost:3001/techlab-service/secured
----

. Client GETs the URL it has been redirected to
+
[source,http]
----
HTTP GET http://keycloak:8180/auth/realms/techlab/protocol/openid-connect/auth?
    client_id=techlab-cli&
    state=9804b94f-2592-40ca-9ee0-e099410613ed&
    redirect_uri=http%3A%2F%2Flocalhost%3A3001%2Ftechlab-service%2Fsecured%3Fauth_callback%3D1&
    scope=openid&
    response_type=code
----

. Resource Owner (End-User) provides Username/Password and POST the data to Authentication Endpoint
+
[source,http]
----
HTTP POST http://keycloak:8180/auth/realms/techlab/login-actions/authenticate?
    session_code=iupzBXwSLTTMEuL0pfmZc043vC1V8H52kGT4zEVvjXM&
    execution=a52aaddb-5e13-41a3-bc2f-498527a4a83b&
    client_id=techlab-cli&
    tab_id=BWKi3QocE3Y
body:
    username:nerd
    password:quirky
----
+
[NOTE]
====
* In the body of the HTTP POST Request the `username` and `password` will be provided to Authorization Endpoint of Keycloak
* After successful authentication Keycloak creates the Redirect URL based on the configuration of the Client and sends
  HTTP 302 Redirect to the Client/Browser
* The generated Authorization Code will be transmitted to browser as `code` attribute in the callback URI
====

. The User Agent transmits the Authorization Code as Query Parameter to the Backend (Client):
+
[source,http]
----
HTTP GET http://localhost:3001/techlab-service/secured?auth_callback=1&
    state=9804b94f-2592-40ca-9ee0-e099410613ed&
    session_state=87e253d8-b242-4294-a5f6-87eeb4578ff9&
    code=7b4f1ad9-7c05-4dc8-a0ea-c417d691a98087e253d8-b242-4294-a5f6-87eeb4578ff94bcea68e-e9cb-41c2-8b8e-c0e09df1985b
----
+
[NOTE]
====
* The Authorization Code will be transmitted to client as `code` attribute in URL
====
+
. Finally the User Agent will be redirected to the Protected Resource and GETs them:
+
[source,http]
----
HTTP GET http://localhost:3001/techlab-service/secured
----


'''
[.text-right]
link:../README.adoc[<- Techlab overview]
