= OAuth 2.0 - Implicit Flow - Lab Solutions

== Q&A

*Q: How is the Access Token transferred to the client?*
The Access Token will be transferred in a Redirection URI to the Client as a Fragment (part behind #).

HTTP 302 (Found), HTTP Response Header `Location`:

[source,http]
----
Location: http://localhost:8082/js-console/#state=f3fd7343-c66d-4e21-9dc4-c740d7eb2c2e&session_state=cbe28121-b478-47a5-b61a-a7d0b190b8f0&id_token=...&access_token=...token_type=bearer&expires_in=900
----


== Captured Flow

==== Initial Request to authentication endpoint

[source,http]
----
HTTP GET http://keycloak:8180/auth/realms/techlab/protocol/openid-connect/auth?
    client_id=js-console&
    redirect_uri=http%3A%2F%2Flocalhost%3A8082%2Fjs-console%2F&
    response_mode=fragment&
    response_type=id_token%20token&
    scope=openid&
    state=b94fc222-cc1d-4f24-82dc-28544988d2ec&
    nonce=ddf74cb3-5073-43e9-b7a9-2e58381afe01
----

[NOTE]
====
* `client_id=js-console`: Identifier of the Client accessing Keycloak
* `redirect_uri`: The URI the User Agent will be redirected to after successful authentication.
* `response_mode=fragment` defines that the callback URL is provided as fragment in URI (part behind #). The other would be `response_mode=uri` which is not recommended due to security issues (bookmarking, history, sent to the server during request). This is Keycloak specific attribute and not part of OAuth 2.0 RFC.
* `response_type=id_token%20token`: `token` enables the the Implicit Flow by defining the response should contain the Access Token itself.
* `scope=openid`: OpenID Connect is enabled, therefore `id_token` is listed in `response_type`
* `state`: Keycloak specific attribute. Used to prevent Cross-site request forgery (CSRF) attacks.
* `nonce`: Required by the OpenID Connect standard for implicit Flow to prevent Reply Attacks. The nonce will generated by client, sent in the authentication request to Keycloak and will be included in the response containing the Access Token.
====


==== Resource Owner (End-User) provides credentials in the displayed login form and POST the data to Keycloak authentication endpoint

[source,http]
----
HTTP POST http://keycloak:8180/auth/realms/techlab/login-actions/authenticate?
    session_code=ADWomLjLiSO_1Muc8vm7yA3LLCY8IfLrCuB4Wk4i9Fk&
    execution=134d2bc0-6036-4566-a435-8cab3f6179dd&
    client_id=js-console&
    tab_id=57ou-1xDuB8
body:
  username:nerd
  password:quirky
----

[NOTE]
====
* In the body of the HTTP POST Request the `username` and `password` will be provided to Authorization Endpoint of Keycloak
* After successful authentication Keycloak creates the Redirect URL based on the configuration of the Client and sends HTTP 302 Redirect to the Client/Browser
====


==== The browser requests the URL to which it has been redirected with the access token received as Fragment from Authorization Server

[source,http]
----
HTTP GET http://localhost:8082/js-console/#
    id_token=eyJhbGciOiJSUz...&
    access_token=eyJhbGciOi...&
    token_type=bearer&
    expires_in=900
    state=b94fc222-cc1d-4f24-82dc-28544988d2ec&
    session_state=71889675-814c-48c9-9a47-95795883aefd&
----

The tokens has been shortened to improve the readability.

[NOTE]
====
* `access_token` is a self-contained Access token which allows the client to access the Protected Resources
* `id_token` is created because OpenID Connect is enabled with `scope=openid` on initial request and `response_type=id_token` was requested -- we cover that in the OpenID connect lab.
* `token_type=bearer`: The created Access Token is of Type bearer and is self-contained.
* `expires_in=900`: Expiration in seconds of the issued access token. Expiration is included in the Access Token itself.
====


==== The Client (JS Adapter: keycloak.js) stores the Access Token locally
The Access Token will be stored in the User Agent in the Cookie `kc-access` and be sent in every subsequent Request to the protected resources as a Authorization Header:

[source,http]
----
Authorization: bearer eyJhbGciOiJSUzI1NiIsInR5c...
----

'''
[.text-right]
link:../README.adoc[<- Techlab overview]
