= OIDC Integration with Python Flask

[NOTE]
====
This Lab is not yet finished.
====

This Lab shows how to integrate Keycloak in a Python3-Flask based application.

## Create new Client in Keycloak

Create a new `confidential Client` in Keycloak with the name `lab-python`.
Ensure that the "Authorization Code Flow" is enabled.
Use `http://localhost:5000/*` as Valid redirect URLs.


## Setup Environment

Clone the GIT Repository:
[source,bash]
```
git clone https://github.com/puzzle/keycloak-techlab-setup.git && cd python-flask-oidc
```


Install Python 3, pip and dependecies in an virtual environment

[source,bash]
```
sudo apt install python3 python3-pip
```


Install the required dependencies

[source,bash]
```
python3 -m venv ./venv
source ./venv/bin/activate
pip3 install -r requirements.txt
```


## Start application
[source,bash]
----
```
cd src
python3 app.py
```

## Configure Application

Create new File under `src/client_secrets.json` with the following content:

[source,json]
----
{
    "web": {
        "client_id": "lab-python",
        "client_secret": "REPLACE_WITH_CLIENT_CREDENTIAL",
        "redirect_uris": [
            "http://localhost:5000/oidc_callback"
        ],
        "auth_uri": "http://keycloak:8180/auth/realms/techlab/protocol/openid-connect/auth",
        "token_uri": "http://keycloak:8180/auth/realms/techlab/protocol/openid-connect/token",
        "token_introspection_uri": "http://keycloak:8180/auth/realms/techlab/protocol/openid-connect/token/introspect",
        "userinfo_uri": "http://keycloak:8180/auth/realms/techlab/protocol/openid-connect/userinfo"
    }
}
----


Replace the `client_secret` with the one generated by Keycloak.

// WIP: Finish the Lab

'''
[.text-right]
link:../README.adoc[<- Techlab overview]