= HTTP Session Handling - Solutions

*Q: How can you revoke the access of the Client to the Protected Ressource immediately?*

A: You can't do this immediately with this setup. The NodeJS Application just validates the Token itself without asking the introspection Endpoint of the Authorization Server on every request. So it just validates if the Access Tokens signature is valid and if it's not yet expired.

The access will remain be as long as long as the Access Token lifetime is not reached.


*Q: Try to find out which cookies are all by the NodeJS backend and by Keycloak.*

A: The following three cookies are all set by Keycloak sets after a Resource Owner successfully authenticated:

* `KEYCLOAK_IDENTITY` JWT Token which contains the user id. Can be decoded with https://jwt.io to see all the information contained. (Session Cookie, does not survive browser restart)
* `KEYCLOAK_SESSION` The HTTP session id per Realm authenticated against. <realm>/<subject of token>/<session-id>.
* `AUTH_SESSION_ID` Cookie which contains the session id (Session Cookie, does not survive browser restart)
* `connect.sid` HTTP session id between the User Agent and the NodeJS backend.

The cookie with name `connect.sid` defines the HTTP Session between the Browser and the NodeJS Backend. Delete it and access the protected endpoint again.


*Q: What happens now? Try to capture the Flow by recording the HTTP traffic of your User Agent. Do you have to authenticate again against Keycloak? Why you have to / don't have to authenticate again?*

A: When an User Agent is redirected to the Authorization Server, Keycloak is validating the values contained in the Cookies listed above (`KEYCLOAK_IDENTITY` is mandatory, `KEYCLOAK_SESSION` or `AUTH_SESSION_ID` are used either). If the HTTP Session between User Agent and Authorization Server is still valid, a new Access Token will be issued.


*Q: Delete the cookie `connect.sid` again, and try to access the protected endpoint again. Whats happening now?*

A: This behaviour can be disabled in the Keycloak Admin Console under `Authentication -> Flows -> Browser -> Cookies -> Disabled`. This means when the session between the User Agent and Authorization Server is no longer active, the Resource Owner has to re-authenticate with his credentials again.


'''
[.text-right]
link:../README.adoc[<- Techlab overview]