= Tokens

== Access Token

From OAuth 2.0 link:https://tools.ietf.org/html/rfc6749#section-1.4[rfc6749]:

[quote, rfc6749]
____
Access tokens are credentials used to access protected resources. An access token is a string representing an authorization issued to the client. The string is usually opaque to the client. Tokens represent specific scopes and durations of access, granted by the resource owner, and enforced by the resource server and authorization server.
____

Access Tokens...

* ...represent specific scopes and durations of access, granted by the resource owner.
* ...may denote an identifier (_by-reference_) or may self-contain (_by-value_) the authorization information in a verifiable manner (e.g using a signature).
* ...provide an abstraction layer and remove the resource server's need to understand a wide range of authentication methods.
* ...Access tokens can have different formats, structures, and methods of utilization.

An example token response:

[code,http]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Cache-Control: no-store
Pragma: no-cache
{
  "access_token":"2YotnFZFEjr1zCsicMWpAA",
  "token_type":"example",
  "expires_in":3600,
  "refresh_token":"tGzv3JOkF0XG5Qx2TlKWIA",
  "example_parameter":"example_value"
}
----

The link:https://tools.ietf.org/html/rfc6749[rfc6749] for OAuth does not further specify access token. For this, the separate link:https://tools.ietf.org/html/rfc6750[rfc6750] (note the sequential number) for bearer tokens was created.

[NOTE]
====
The main benefit of self-contained Access Tokens is that the authorization can be done stateless and without any lookups.

For invalidating existing self-contained tokens an additional lookup must be performed. This lookup is called _token introspection_ and we will cover that in the hand-on parts of this lab.
====

== Bearer (Access) Token

Actually the bearer token is something like the default access token type of OAuth 2.0. That's not surprising, the specification for bearer tokens was created in conjunction with the OAuth specification.

The definition of _bearer_ from link:https://tools.ietf.org/html/rfc6750[rfc6750]:

[quote, rfc6750]
____
Any party in possession of a bearer token (a "bearer") can use it to get access to the associated resources (without demonstrating possession of a cryptographic key). To prevent misuse, bearer tokens need to be protected from disclosure in storage and in transport.
____

Thus, it is higly important that bearer access tokens be confidently in-transit as in-rest, and must be known only to the client, the Authorization Server, and the Protected Resource. Any client in possession of an access token can invoke the corresponding protected resources. So this is why the security of OAuth 2.0 (using bearer tokens) is largely based on the secure use of TLS.

Bearer access tokens can be submitted by the client to the protected resource in three ways:

* As http header field ```Authorization: Bearer mF_9.B5f-4.1JqM```
* In the http body as form-encoded field: ```access_token=mF_9.B5f-4.1JqM```
* As URI query parameter: ```/resource?access_token=mF_9.B5f-4.1JqM```

Response with an Access and Refresh Token (also note the field `token_type`):

[source,http]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Cache-Control: no-store
Pragma: no-cache

{
  "access_token":"mF_9.B5f-4.1JqM",
  "token_type":"Bearer",
  "expires_in":3600,
  "refresh_token":"tGzv3JOkF0XG5Qx2TlKWIA"
}
----

Security issues with bearer tokens:

* Manipulation of tokens (e.g. the lifetime, scopes etc.).
* Tokens incorrectly contain trusted data.
* Use tokens for a different protected resource than they were originally issued.
* "Old" tokens are used again.

Important points to note when using bearer tokens:

* The bearer tokens must always be kept secure by the clients.
* Avoid putting bearer tokens into cookies. There are a lot of pitfalls using cookies (flags)!
* Use secure TLS in any case.
* Use short lifespan for bearer tokens (<1h).
* Deliver bearer tokens to clients as http body or header. Avoid URL parameters, these are not sufficiently protected (e.g. bookmarks, history, logs, etc.).

== Refresh Token

From link:https://tools.ietf.org/html/rfc6749#section-1.5[rfc6749]:

[cite,rfc6749]
____
Refresh tokens are credentials used to obtain access tokens. Refresh tokens are issued to the client by the authorization server and are used to obtain a new access token when the current access token becomes invalid or expires, or to obtain additional access tokens with identical or narrower scope (access tokens may have a shorter lifetime and fewer permissions than authorized by the resource owner). Issuing a refresh token is optional at the discretion of the authorization server. If the authorization server issues a refresh token, it is included when issuing an access token.
____

The implicit grant does not support the issuance of refresh tokens because it's never a confidential client.

[NOTE]
====
Silent Refresh -- If you have the need to automatically refresh your access token using implicit flow, you can try to implement a silent refresh. A silent refresh does request a new access token in the background. See this link:https://www.scottbrady91.com/OpenID-Connect/Silent-Refresh-Refreshing-Access-Tokens-when-using-the-Implicit-Flow[blog] for more details.
====

== ID Token
From link:https://openid.net/specs/openid-connect-core-1_0.html#IDToken[openid-connect specification]:

[cite,openid-connect 1.0 specification]
____
The primary extension that OpenID Connect makes to OAuth 2.0 to enable End-Users to be Authenticated is the ID Token data structure. The ID Token is a security token that contains Claims about the *Authentication* of an End-User by an Authorization Server when using a Client, and potentially other requested Claims. The ID Token is represented as a JSON Web Token (JWT)
____

An ID Token is a self-contained token for all OAuth 2.0 flows and looks something like this:

[source,http]
----
  {
   "iss": "https://server.example.com",
   "sub": "24400320",
   "aud": "s6BhdRkqt3",
   "nonce": "n-0S6_WzA2Mj",
   "exp": 1311281970,
   "iat": 1311280970,
   "auth_time": 1311280969,
   "acr": "urn:mace:incommon:iap:silver"
  }
----

The claims (`iss`, `sub` etc.) are very well explained in the link:https://openid.net/specs/openid-connect-core-1_0.html#IDToken[specification].

An ID token does normally not contain any access information.

=== JSON Web Token (JWT)

JSON Web Tokens are specified in link:https://tools.ietf.org/html/rfc7519[rfc7519]:

[cite,rfc7519]
____
JSON Web Token (JWT) is a compact, URL-safe means of representing claims to be transferred between two parties. The claims in a JWT are encoded as a JSON object that is used as the payload of a JSON Web Signature (JWS) structure or as the plaintext of a JSON Web Encryption (JWE) structure, enabling the claims to be digitally signed or integrity protected with a Message Authentication Code (MAC) and/or encrypted.
____

Thus JWT represent a form of self-contained tokens. OpenID connect specifies the required claims for it's JWT tokens. link:https://jwt.io/[JWT.io] is a reference implementation for this rfc7519 and allows you to decode, verify and generate JWT.

[TIP]
====
If you want to verify the JWT signature of a token issued by Keycloak with JWT.io you can do this as follows:

. Retrieving the realm RSA public key:
`curl -v http://keycloak:8180/auth/realms/techlab/protocol/openid-connect/certs | jq`
. Create a certificate file (.pem): The `x5c` filed value is copied between `-----BEGIN CERTIFICATE-----` and `-----END CERTIFICATE-----` directives (using line breaks to separate directives an key).
. Copy & paste this pem-String into JWT.io public-key field.
====

== Keycloak Tokens

Keycloak issues JWT for access and of course ID tokens.

Some important chapters about Keycloak and it's tokens are:

* link:https://www.keycloak.org/docs/latest/server_admin/index.html#_timeouts[Session and token timeouts]
* link:https://www.keycloak.org/docs/latest/server_admin/index.html#_offline-access[Offline access]


== Lab

There is a OAuth 2.0 extension for _token introspection_ in link:https://tools.ietf.org/html/rfc7662[rfc7662].

[cite,rfc7662]
____
This specification defines a method for a protected resource to query an OAuth 2.0 authorization server to determine the active state of an OAuth 2.0 token and to determinemeta-information about this token. OAuth 2.0 deployments can use this method to conveyinformation about the authorization context of the token from the authorization server tothe protected resource.
____

This endpoint is specially useful for use cases, where it must be checked whether a token was not revoked.

Try to implement a token introspection for the following token:

[source,sh]
----
export access_token=$( \
curl -s -X POST http://keycloak:8180/auth/realms/techlab/protocol/openid-connect/token \
    -H "content-type: application/x-www-form-urlencoded" \
    -d "client_id=techlab-cli&username=nerd&password=quirky&grant_type=password&scope=openid" | jq --raw-output '.access_token')
----

////
curl -s -X POST http://keycloak:8180/auth/realms/techlab/protocol/openid-connect/token/introspect \
-u "techlab-cli-confidential:f3a9bd60-2acd-4726-aaf2-ffddc5478827" \
-H "Content-Type: application/x-www-form-urlencoded" \
-d "token=${access_token}" | jq
////


Go to Keycloaks http://keycloak:8180/auth/admin/master/console/#/realms/techlab/sessions/realm[View with Active Sessions] and invalidate all Sessions by clickint `Logout all`.

Verify the same Access Token again by Introspection Endpoint. The token should be no longer active.

// TODO: Show Scopes intersections client/users

'''
[.text-right]
link:../README.adoc[<- Techlab overview] | 
link:./05_secure-applications.adoc[Secure applications ->]