= Secure a Spring Boot based restful API

This lab is based on `service-springboot-rest` of the link:https://github.com/keycloak/keycloak-quickstarts.git[Keycloak quickstarts].

To make it short: The Spring examples of Keycloak are still a bit flawed. We will have to adapt some things for which an IDE is practical. But you can do it a bit less comfortable without it.

In this lab we are going to create a restful _Resource Server_ and requesting it's resources using `cURL` as _Client_. The credentials of _Resource Owner_ `Nerd` will be used in combination with the _Resource Owner Credentials_ Flow to obtain a valid token.

ifndef::env-github[]
[ditaa, "../images/springboot-rest-flow", svg]
----
          +---------------------+
          |                     |
          | Resource Owner:Nerd |
          |                     |
          +----------+----------+
                     |                             +----------------------+
                     |               +------------>+                      |
                     | Credentials   |             | Auth Server:Keycloak |
                     |               | Token       |                      |
                     v               v             +----------------------+
+--------------------+---------------+--+
|                                       |
| Client(cURL):techlab+cli+confidential |
|                                       |
+------------------------------------+--+
                                     ^             +-------------------------------------+
                                     | Resource    |                                     |
                                     |             | Resource Server:lab+spring+rest+api |
                                     +------------>+                                     |
                                                   +-------------------------------------+
----
endif::env-github[]
ifdef::env-github[]
image::../images/springboot-rest-flow.svg[]
endif::env-github[]

For this lab it's a good idea to start with the client definition for Keycloak. So open your link:http://keycloak:8180[Administration Console] and create a new client named `lab-spring-rest-api`. You have learned the basics of what important settings an *API client* needs in the previous theoretical labs (type of flows/grant, type of clients etc.). For a REST API we are going to use a special client type called `bearer-only`. This is a Keycloak specific client.

[TIP]
====
In Keycloak there is a third _Access Type_ for Clients named `bearer-only`. `bearer-only` is specific to Keycloak and not part of OAuth 2.0 or OpenID Connect standards. This configuration is used for services which expect a Bearer Token (an Access Token) in every request. If no token is provided the Service will return immediately a HTTP 401 and will not redirect the client to a login form. The redirection to Login form will be done by another part, typically by the frontend.
====

////
Create a new client `lab-spring-rest-api` with _Access Type_ `bearer-only`.
////

Next we will take a look into the source code:

As common for spring boot applications there is a application configuration file `application.properties` at `src/main/resources/`. This contains the Keycloak settings. Open it and figure out what you may have to adjust.

[TIP]
====
The `client_id` correlates with the property `keycloak.resource` in `application.properties`.
====

[TIP]
====
Check the _Installation_ tab within your Client settings of your Keycloak Administration Console to see all relevant Keycloak adapter settings of your Client definition.
====

////
keycloak.realm=techlab --> (fancy exception possible if not set: "Error when sending request to retrieve realm keys")
keycloak.auth-server-url=http://keycloak:8180/auth
keycloak.ssl-required=none
keycloak.resource=lab-spring-rest-api
keycloak.public-client=true
keycloak.bearer-only=true
////

Try to build and run your api:

[source,sh]
----
mvn spring-boot:run
----

[TIP]
====
Failed? If you got an error like `_Source/Target option 5 is no longer supported. Use 7 or later._`. Add the following into your `<properties>` section within `pom.xml` (adjust the Java version to your local JDK version):

[source,xml]
----
<java.version>1.11</java.version>
<maven.compiler.source>1.11</maven.compiler.source>
<maven.compiler.target>1.11</maven.compiler.target>
----
====

[TIP]
====
Failed? If you got an error like `_Error creating bean with name 'org.keycloak.adapters.springboot.KeycloakAutoConfiguration': Unsatisfied dependency expressed through method 'setKeycloakSpringBootProperties' parameter 1_`. Congratulations, you met your propably first link:https://issues.jboss.org/browse/KEYCLOAK-11282[Keycloak Bug]. Copy the Java class `KeycloakConfig.java` from the `techlab-content` git Repository into the project source:

[source,sh]
----
cp KeycloakConfig.java ../keycloak-quickstarts/service-springboot-rest/src/main/java/org/keycloak/quickstart/springboot
----

Additionally it may be a good idea to update to the latest spring version. In the pom.xml change the spring version to the following (see https://repo.spring.io/release/org/springframework/boot/spring-boot/):

[source,xml]
----
<springboot-version>2.2.4.RELEASE</springboot-version>
----
====

After successfully starting your spring boot application you should have a running and accessible endpoint at http://localhost:8081/public. The endpoint under http://localhost:8081/products is protected and returns a `401 Unauthorized` as it expects a User with the role `user` assigned.

Try to get a access token as environment variable using cURL for the `techlab-cli-confidential` client and `nerd` user:

[source,sh]
----
export access_token=$( \
    curl -X POST <??the correct endpoint regarding to the protocol flow??> \
    -H 'Authorization: Basic <??client authentication if used as base64 encoded value??>' \
    -H 'content-type: application/x-www-form-urlencoded' \
    -d 'username=nerd&password=quirky&grant_type=<??grant type??>' | \
    jq --raw-output '.access_token' \
)
----

[TIP]
====
All OAuth 2.0/OpenID Connect specific information for your Keycloak setup is available at: http://keycloak:8180/auth/realms/techlab/.well-known/openid-configuration.
====

[TIP]
====
Make sure you use the client `techlab-cli-confidential` to create an Access Token. `bearer-only` endpoints can't issue new tokens. They always expect an Access Token in every request received from a Client. If the Token is invalid it will return immediately an HTTP 401 Unauthorized.
====

[TIP]
====
Create your Basic-Auth credentials with the following command:
`echo -n "<client-id>:<client-secret>" | base64 -w0`
====

////
echo -n "techlab-cli-confidential:8188f1b5-b64a-4b4d-a404-938acf8d003f" | base64 -w0

export access_token=$(\
   curl -X POST http://keycloak:8180/auth/realms/techlab/protocol/openid-connect/token \
   -H 'Authorization: Basic dGVjaGxhYi1jbGktY29uZmlkZW50aWFsOjgxODhmMWI1LWI2NGEtNGI0ZC1hNDA0LTkzOGFjZjhkMDAzZg==' \
   -H 'content-type: application/x-www-form-urlencoded' \
   -d 'username=nerd&password=quirky&grant_type=password' | jq --raw-output '.access_token' \
)

echo $access_token
////

[TIP]
====
Do you know https://jwt.io yet? Try to decode and understand your access token using jwt.io.
====

With the access token returned you are now able to send a request to the api:

[source,sh]
----
curl -v -X GET \
  http://localhost:8081/products \
  -H "Authorization: <??>
----

////
curl -v -X GET \
  http://localhost:8081/products \
  -H "Authorization: Bearer "$access_token
////

Now you are authenticated but not authorized. Find out what else is missing. Look at the source code and try to understand where and how Policy Enforcement is defined.

////
It's part of the application.properties file. The role and mapping of the user to this role is missing.
////

As you may have noticed, the Role `user` for the endpoint `/products` is checked. We have not created a corresponding role nor assigned the user to this role. Fix this by creating a Realm Role and assign the user `nerd` to this role.

Is it working? Good.

Assuming the role `user` is not a general role of our organization (realm). Now if other applications come with similar roles, we would have to introduce a naming concept - which is really not very pretty. Keycloak offers the possibility to define the roles also on client level. Try to adjust the lab accordingly. See Keycloak Documentation link:https://www.keycloak.org/docs/latest/server_admin/#client-roles[for Roles] and check Keycloak Java Adapater link:https://www.keycloak.org/docs/latest/securing_apps/index.html#_java_adapter_config[configuration options].

[TIP]
====
There is one important adapter configuration option you have to set in your `application.properties` file.
====

////
Create a new `user` role at client level. Assign the new role to the user.
Adjust the application properties to use client roles: keycloak.use-resource-role-mappings=true
////

It is still working? Congratulations, you have successfully finished this lab.

For more and detailed information please see the link:https://www.keycloak.org/docs/latest/securing_apps/index.html#_spring_boot_adapter[Keycloak documentation] for adapters. There is also a link:https://www.keycloak.org/docs/latest/securing_apps/index.html#_spring_security_adapter[Spring Security adapter].

'''
[.text-right]
link:../README.adoc[<- Techlab overview] | 
link:./05b_jee-rest-api.adoc[Secure JEE restful API ->]
